const AboutTeamAPI = [
    {
      id: 1,
      image: "images/team-1.jpg",
      facebook: "https://www.facebook.com",
      instagram: "https://www.instagram.com",
      youtube: "https://www.youtube.com",
      twitter: "https://www.twitter.com",
      name: "Walter White",
      profile: "CHIEF EXECUTIVE OFFICER",
      description:"Amet labore numquam corrupti est. Nostrum amet voluptas consectetur dolor voluptatem architecto distinctio consequuntur eligendi. Quam impedit enim aut nesciunt aut dicta quam exercitationem. Reprehenderit exercitationem magnam. Ullam similique ut voluptas totam nobis porro accusamus nulla omnis.",
    },
    {
      id: 2,
      image: "images/team-2.jpg",
      facebook: "https://www.facebook.com",
      instagram: "https://www.instagram.com",
      youtube: "https://www.youtube.com",
      twitter: "https://www.twitter.com",
      name: "Sarah Jhonson",
      profile: "PRODUCT MANAGER",
      description:"Amet labore numquam corrupti est. Nostrum amet voluptas consectetur dolor voluptatem architecto distinctio consequuntur eligendi. Quam impedit enim aut nesciunt aut dicta quam exercitationem. Reprehenderit exercitationem magnam. Ullam similique ut voluptas totam nobis porro accusamus nulla omnis.",
    },
    {
      id: 3,
      image: "images/team-3.jpg",
      facebook: "https://www.facebook.com",
      instagram: "https://www.instagram.com",
      youtube: "https://www.youtube.com",
      twitter: "https://www.twitter.com",
      name: "William Anderson",
      profile: "CHEFS",
      description:"Amet labore numquam corrupti est. Nostrum amet voluptas consectetur dolor voluptatem architecto distinctio consequuntur eligendi. Quam impedit enim aut nesciunt aut dicta quam exercitationem. Reprehenderit exercitationem magnam. Ullam similique ut voluptas totam nobis porro accusamus nulla omnis.",
    },
    {
      id: 4,
      image: "images/team-4.jpg",
      facebook: "https://www.facebook.com",
      instagram: "https://www.instagram.com",
      youtube: "https://www.youtube.com",
      twitter: "https://www.twitter.com",
      name: "Amanda Jepson",
      profile: "ACCOUNTANT",
      description:"Amet labore numquam corrupti est. Nostrum amet voluptas consectetur dolor voluptatem architecto distinctio consequuntur eligendi. Quam impedit enim aut nesciunt aut dicta quam exercitationem. Reprehenderit exercitationem magnam. Ullam similique ut voluptas totam nobis porro accusamus nulla omnis.",
    },
    {
      id: 5,
      image: "images/team-5.jpg",
      facebook: "https://www.facebook.com",
      instagram: "https://www.instagram.com",
      youtube: "https://www.youtube.com",
      twitter: "https://www.twitter.com",
      name: "Niall Katz",
      profile: "MARKETING",
      description:"Amet labore numquam corrupti est. Nostrum amet voluptas consectetur dolor voluptatem architecto distinctio consequuntur eligendi. Quam impedit enim aut nesciunt aut dicta quam exercitationem. Reprehenderit exercitationem magnam. Ullam similique ut voluptas totam nobis porro accusamus nulla omnis.",
    },
    {
      id: 6,
      image: "images/team-6.jpg",
      facebook: "https://www.facebook.com",
      instagram: "https://www.instagram.com",
      youtube: "https://www.youtube.com",
      twitter: "https://www.twitter.com",
      name: "Demi Lewis",
      profile: "CHEFS",
      description:"Amet labore numquam corrupti est. Nostrum amet voluptas consectetur dolor voluptatem architecto distinctio consequuntur eligendi. Quam impedit enim aut nesciunt aut dicta quam exercitationem. Reprehenderit exercitationem magnam. Ullam similique ut voluptas totam nobis porro accusamus nulla omnis.",
    },
  ];
  export default AboutTeamAPI;